name: rishika
channels:
  - conda-forge
dependencies:
  - anyio=4.9.0=pyh29332c3_0
  - aom=3.9.1=he0c23c2_0
  - apricot-select=0.6.1=pyhd8ed1ab_2
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py310ha8f682b_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - arviz=0.21.0=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.9.0=h5e0e64b_7
  - aws-c-cal=0.9.0=hd8a8e38_1
  - aws-c-common=0.12.3=h2466b09_0
  - aws-c-compression=0.3.1=h5d0e663_5
  - aws-c-event-stream=0.5.4=h2c6ec7e_9
  - aws-c-http=0.10.1=h2d86538_1
  - aws-c-io=0.19.0=hfdfeb85_2
  - aws-c-mqtt=0.13.0=hef5cf85_3
  - aws-c-s3=0.7.17=h3b2a8e2_2
  - aws-c-sdkutils=0.2.3=h5d0e663_5
  - aws-checksums=0.2.7=h5d0e663_1
  - aws-crt-cpp=0.32.5=h5528c5b_3
  - aws-sdk-cpp=1.11.510=hf5dcd55_8
  - babel=2.17.0=pyhd8ed1ab_0
  - bcrypt=4.3.0=py310hc226416_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=hfd34d9b_1
  - bokeh=3.7.3=pyhd8ed1ab_0
  - bottleneck=1.4.2=py310hb0944cc_0
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - brotli-python=1.1.0=py310h9e98ed7_2
  - bzip2=1.0.8=h2466b09_7
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.4.26=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.17.1=py310ha8f682b_0
  - cftime=1.6.4=py310hb0944cc_1
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.0=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - cma=4.0.0=pyhecae5ae_0
  - cmasher=1.8.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorspacious=1.1.2=pyhecae5ae_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py310hc19bc0b_0
  - corner=2.2.3=pyhd8ed1ab_1
  - cryptography=45.0.2=py310h25a5809_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py310ha8f682b_0
  - dask=2025.1.0=pyhd8ed1ab_0
  - dask-core=2025.1.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.14=py310h9e98ed7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - distributed=2025.1.0=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - ffmpeg=7.1.1=gpl_h37769ee_905
  - filelock=3.18.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.0=py310h38315fa_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=h57928b3_1
  - fribidi=1.0.10=h8d14728_0
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=hed59a49_0
  - git=2.43.0=h57928b3_0
  - glib=2.84.1=he8f994d_1
  - glib-tools=2.84.1=h4394cf3_1
  - gpyreg=1.0.2=pyhd8ed1ab_1
  - graphite2=1.3.13=h63175ca_1003
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5netcdf=1.6.1=pyhd8ed1ab_0
  - h5py=3.12.1=nompi_py310h972678a_103
  - harfbuzz=11.2.1=h8796e6f_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.4=nompi_hd5d9e70_105
  - hmmlearn=0.3.0=py310h00ffb61_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - imageio=2.37.0=pyhfb79c49_0
  - imageio-ffmpeg=0.6.0=pyhd8ed1ab_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.36.0=pyh9ab4c32_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.0=pyhd8ed1ab_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310h5588dad_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.0.0=py310h5588dad_8
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=py310h5588dad_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.2=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py310hc19bc0b_2
  - krb5=1.21.3=hdf4eb48_0
  - lame=3.100=hcfcfb64_1003
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250127.1=cxx17_h4eb7d71_0
  - libaec=1.1.3=h63175ca_0
  - libarrow=20.0.0=hde72ee7_3_cpu
  - libarrow-acero=20.0.0=h7d8d6a5_3_cpu
  - libarrow-dataset=20.0.0=h7d8d6a5_3_cpu
  - libarrow-substrait=20.0.0=hb76e781_3_cpu
  - libblas=3.9.0=31_h641d27c_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=31_h5e41251_mkl
  - libclang13=20.1.5=default_h6e92b77_1
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.13.0=h88aaa65_0
  - libdeflate=1.24=h76ddb4d_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.0=he0c23c2_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libglib=2.84.1=hbc94333_1
  - libgoogle-cloud=2.36.0=hf249c01_1
  - libgoogle-cloud-storage=2.36.0=he5eb982_1
  - libgrpc=1.71.0=h8c3449c_1
  - libhwloc=2.11.1=default_h8125262_1000
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=31_h1aa476e_mkl
  - liblzma=5.8.1=h2466b09_1
  - liblzma-devel=5.8.1=h2466b09_1
  - libnetcdf=4.9.2=nompi_h5bdc103_116
  - libogg=1.3.5=h2466b09_1
  - libopus=1.5.2=h2466b09_0
  - libparquet=20.0.0=ha850022_3_cpu
  - libpng=1.6.47=h7a4582a_0
  - libprotobuf=5.29.3=he9d8c4a_1
  - libre2-11=2024.07.02=hd248061_3
  - librsvg=2.58.4=h5ce5fed_3
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.49.2=h67fdade_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.21.0=hbe90ef8_0
  - libtiff=4.7.0=h05922d8_5
  - libtorch=2.7.0=cpu_mkl_hf54a72f_100
  - libusb=1.0.28=h1839187_1
  - libutf8proc=2.10.0=hf9b99b7_0
  - libuv=1.50.0=h2466b09_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.13.8=h442d1da_0
  - libxslt=1.1.39=h3df6e99_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_2
  - littleutils=0.2.4=pyhd8ed1ab_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py310hd8baafb_0
  - lz4-c=1.10.0=h2466b09_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=3.0.2=py310h38315fa_1
  - matplotlib=3.10.3=py310h5588dad_0
  - matplotlib-base=3.10.3=py310h37e0a56_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - mkl=2024.2.2=h66d3029_15
  - moviepy=1.0.3=pyhd8ed1ab_1
  - mpl-interactions=0.23.2=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py310hc19bc0b_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - narwhals=1.40.0=pyhe01879c_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.2=nompi_py310h39c5739_101
  - networkx=3.4.2=pyh267e887_2
  - nose=1.3.7=py_1006
  - notebook=7.4.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.2.6=py310h4987827_0
  - openh264=2.6.0=hb17fa0b_0
  - openjpeg=2.5.3=h4d64b90_0
  - openpyxl=3.1.2=py310h8d17308_0
  - openssl=3.5.0=ha4e3fda_1
  - optree=0.15.0=py310hc19bc0b_0
  - orc=2.1.2=h35764e3_0
  - outdated=0.2.2=pyhd8ed1ab_2
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py310hb4db72f_3
  - pandas-flavor=0.7.0=pyhd8ed1ab_0
  - pandoc=3.7.0.1=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.3=h0c53d3b_1
  - paramiko=3.4.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.45=h99c9b8b_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=10.4.0=py310h3e38d90_1
  - pingouin=0.5.5=pyhd8ed1ab_0
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.46.0=had0cd8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.8=pyhe01879c_0
  - plotly=6.1.0=pyhd8ed1ab_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - pomegranate=1.0.0=pyhd8ed1ab_3
  - proglog=0.1.10=pyhaa61c55_0
  - prometheus_client=0.22.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - psutil=7.0.0=py310ha8f682b_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=h2466b09_4
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=20.0.0=py310h5588dad_0
  - pyarrow-core=20.0.0=py310h399dd74_0_cpu
  - pybads=1.0.5=pyhd8ed1ab_1
  - pybind11=2.13.6=pyh1ec8472_2
  - pybind11-global=2.13.6=pyhab904b8_2
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pynacl=1.5.0=py310h8576403_4
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=5.15.11=py310h936fe8c_0
  - pyqt5-sip=12.17.0=py310h9e98ed7_0
  - pyside6=6.9.0=py310hc1b6536_0
  - pysocks=1.7.1=pyh09c184e_7
  - pytest=8.3.5=pyhd8ed1ab_0
  - pytest-mock=3.14.0=pyhd8ed1ab_1
  - pytest-rerunfailures=15.1=pyhd8ed1ab_0
  - python=3.10.17=h8c5b53a_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=6_cp310
  - pytorch=2.7.0=cpu_mkl_py310_h8e04999_100
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=307=py310h9e98ed7_3
  - pywinpty=2.0.15=py310h9e98ed7_0
  - pyyaml=6.0.2=py310h38315fa_2
  - pyzmq=26.4.0=py310h656833d_0
  - qhull=2020.2=hc790b64_5
  - qt-main=5.15.15=h9151539_4
  - qt6-main=6.9.0=h02ddd7d_3
  - qtconsole=5.6.1=pyhd8ed1ab_1
  - qtconsole-base=5.6.1=pyha770c72_1
  - qtpy=2.4.3=pyhd8ed1ab_0
  - re2=2024.07.02=haf4117d_3
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.25.0=py310hed05c55_0
  - schedule=1.2.2=pyhd8ed1ab_1
  - scikit-learn=1.6.1=py310hf2a6c47_0
  - scipy=1.15.2=py310h15c175c_0
  - sdl2=2.32.54=he0c23c2_0
  - sdl3=3.2.14=ha4196fd_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=75.8.2=pyhff2d567_0
  - sip=6.10.0=py310h9e98ed7_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h7e360cc_0
  - snappy=1.2.1=h500f7fa_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py310hb0944cc_0
  - svt-av1=3.0.2=he0c23c2_0
  - sympy=1.14.0=pyh04b8f61_5
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2021.12.0=hc790b64_4
  - tblib=3.1.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5=py310ha8f682b_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250516=pyhd8ed1ab_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=16.0.0=py310ha8f682b_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.4.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_26
  - vc14_runtime=14.42.34438=hfd919c2_26
  - vs2015_runtime=14.42.34438=h7142326_26
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xarray=2024.7.0=pyhd8ed1ab_0
  - xarray-einstats=0.8.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.8.1=h208afaa_1
  - xz-tools=5.8.1=h2466b09_1
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=ha9f60a1_7
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=h2466b09_2
  - zstandard=0.23.0=py310ha8f682b_2
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - asciitree==0.3.3
      - autograd==1.6.2
      - cython==3.0.6
      - fasteners==0.19
      - future==0.18.3
      - isosplit6==0.1.4
      - llvmlite==0.41.1
      - neo==0.13.1
      - numba==0.58.1
      - numcodecs==0.13.0
      - open-ephys-python-tools==0.1.12
      - opencv-python==4.10.0.84
      - probeinterface==0.2.23
      - pyenchant==3.2.2
      - quantities==0.15.0
      - spikeextractors==0.9.11
      - spikefeatures==0.1.2
      - spikeinterface==0.100.8
      - spikemetrics==0.2.4
      - spikesorters==0.4.5
      - spiketoolkit==0.7.7
      - zarr==2.17.2
      - zmq==0.0.0
prefix: C:\Users\dlab\miniforge3\envs\rishika
